### PR TITLE
Remove the cruft

### LINKED ISSUE #119: Remove the cruft
The pledgeservice is full of an aborted attempt to make it into the primary web site.  Mostly these are files in the markup/ and assets/ directory.  Not a priority, but it would simplify the number of source files, which might be nice.

### PR DESCRIPTION
**Pull request by erinzm**
Fixes #119

### CODE REVIEW

**Comment by aaronlifshin** [comment]
the idea of that commit is removing the old visible front-end-type pages from pledgeservice?

**Comment by erinzm** [comment]
Yep, and the pics too.

**Comment by aaronlifshin** [comment]
deployed to pledgedev.mayday.us

**Comment by erinzm** [comment]
Sure it's deployed? All the removed pages still show up, like https://pledgedev.mayday.us/about-us, as well as the pictures and stuff.

**Comment by aaronlifshin** [comment]
You know what, I had forgotten a step.  It's redone now and on pledgedev.

A

**Pull request merged**
