### PR TITLE
Using a gemfile for managing Sass

### PR DESCRIPTION
**Pull request by erinzm**
Just putting it in a Gemfile; ensures that havoc does not ensue.

### CODE REVIEW

**Comment by brad** [comment]
Is `bundle` a ruby built-in? I thought it had to be gem installed as well.

**Comment by jtolio** [comment]
bundle comes from the bundler gem, yeah, but it's fairly widely installed

**Comment by erinzm** [comment]
I had several problems installing sass properly; it worked fine if I used a bundle ;)
It's probably _completely_ specific to **my** setup; I just don't want it to happen to some other contributor.

**Comment by erinzm** [comment]
Hmmm. Looked into it; seems like it's bad practice. Closing the PR.

**Pull request closed without merging**
