### PR TITLE
Switch Travis to our new IRC channel!

### PR DESCRIPTION
**Pull request by erinzm**
Just nice to have.
I think you were asking about this @aaronlifshin?

### CODE REVIEW

**Comment by brad** [comment]
Good call!

**Comment by erinzm** [comment]
I thought I saw you remark that Travis wasn't doing this, so I did this
patch :)

**Comment by aaronlifshin** [comment]
ok so this is all deployed to pledgedev at the moment, once the jinja email stuff is tested, we can push it live.

**Comment by erinzm** [comment]
@aaronlifshin This is just a Travis config. It didn't need to be deployed to work :)

**Pull request merged**
