### PR TITLE
Jinja email templates

### PR DESCRIPTION
**Pull request by erinzm**
Addresses #109. @brad does this look OK?

### CODE REVIEW

**Comment by erinzm** [comment]
Oh, wait, I haven't added the new templates yet. Better do that :)

**Comment by erinzm** [comment]
Yep, fixed those.

**Comment by brad** [comment]
The code looks good to me on the service, but have you tested it? It looks like it's causing 500 errors, judging by the test results.

**Comment by erinzm** [comment]
How would it cause 500s, unless Jinja's doing something bad?
BTW why isn't the whole email-sending thing wrapped in a try...catch?

**Comment by brad** [comment]
I'm going to review this locally.

**Comment by brad** [comment]
Looks like it's throwing up due to non-ascii characters in the email:

```
>> ERROR    2014-07-18 03:31:15,530 webapp2.py:1528] 'ascii' codec can't decode byte 0xe2 in position 760: ordinal not in range(128)
>> Traceback (most recent call last):
>> File "/opt/google-appengine-python/lib/webapp2-2.3/webapp2.py", line 1511, in __call__
>>     rv = self.handle_exception(request, response, e)
>>   File "/opt/google-appengine-python/lib/webapp2-2.3/webapp2.py", line 1505, in __call__
>>     rv = self.router.dispatch(request, response)
>>   File "/opt/google-appengine-python/lib/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
>>     return route.handler_adapter(request, response)
>>   File "/opt/google-appengine-python/lib/webapp2-2.3/webapp2.py", line 1077, in __call__
>>     return handler.dispatch()
>>   File "/opt/google-appengine-python/lib/webapp2-2.3/webapp2.py", line 547, in dispatch
>>     return self.handle_exception(e, self.app.debug)
>>   File "/opt/google-appengine-python/lib/webapp2-2.3/webapp2.py", line 545, in dispatch
>>     return method(*args, **kwargs)
>> File "/home/brad/projects/mayday/pledgeservice/build/handlers.py", line 291, in post
>>     id, auth_token, receipt_url = pledge_helper(self, data, stripe_customer_id, stripe_charge_id, None, None)
>>   File "/home/brad/projects/mayday/pledgeservice/build/handlers.py", line 208, in pledge_helper
>>     text_template = jinja2.Template(open('email/thank-you.txt').read())
>>   File "/opt/google-appengine-python/lib/jinja2-2.6/jinja2/environment.py", line 831, in __new__
>>     return env.from_string(source, template_class=cls)
>> File "/opt/google-appengine-python/lib/jinja2-2.6/jinja2/environment.py", line 769, in from_string
>>     return cls.from_code(self, self.compile(source), globals, None)
>>   File "/opt/google-appengine-python/lib/jinja2-2.6/jinja2/environment.py", line 479, in compile
>>     source = self._parse(source, name, filename)
>> File "/opt/google-appengine-python/lib/jinja2-2.6/jinja2/environment.py", line 398, in _parse
>>     return Parser(self, source, name, _encode_filename(filename)).parse()
>>   File "/opt/google-appengine-python/lib/jinja2-2.6/jinja2/parser.py", line 32, in __init__
>>     self.stream = environment._tokenize(source, name, filename, state)
>> File "/opt/google-appengine-python/lib/jinja2-2.6/jinja2/environment.py", line 429, in _tokenize
>>     source = self.preprocess(source, name, filename)
>>   File "/opt/google-appengine-python/lib/jinja2-2.6/jinja2/environment.py", line 423, in preprocess
>>     self.iter_extensions(), unicode(source))
>> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 760: ordinal not in range(128)
>> INFO     2014-07-18 03:31:15,539 module.py:612] default: "POST /r/pledge HTTP/1.1" 500 228
```

I fear that if we had this stuff wrapped in a try/catch we may not have seen this error :wink:

**Comment by erinzm** [comment]
This is probably good to know :wink:

**Comment by erinzm** [comment]
Hmm, looks like I have to just unicodify the template sources and then wrap
the variables in `unicode(..., "utf-8")`.

**Comment by erinzm** [comment]
@brad Tests aren't passing but it works locally.

**Comment by erinzm** [comment]
@brad Travis says it's OK, it works OK locally. Can we pull and deploy to **dev** to test?

**Comment by erinzm** [comment]
Added Unicode on email to be sent to.

**Comment by erinzm** [comment]
@brad 4ed136a blew up a bunch of stuff: apparently a lot of functions can't handle Unicode strings.

**Comment by brad** [comment]
I'm checking out 4ed136a2ad27fc5a718265fe7292e4de749ea363 now, can't believe how much stuff it breaks!

**Comment by erinzm** [comment]
Thanks for the PR @brad

**Comment by brad** [comment]
No problem, I think maybe we should just do a `.encode('utf-8')` on the email and name. That's how it was before, except only for the name. I think what that does is convert the unicode code into the actually nice looking character, e.g. converting \u00E1 to á

**Comment by erinzm** [comment]
Is this merge-able yet @brad?

**Comment by erinzm** [comment]
Does this look OK @jwhite66?

**Comment by brad** [comment]
@ArchimedesPi My last comment hasn't been addressed yet. This is probably fine as is though.

**Comment by jwhite66** [comment]
I'm a little concerned that there is enough being changed in this, that it should get careful review and a careful test.  I'd like to get our current effort on addresses done, and then maybe get this code live on dev for some testing and more review.  (And it'd be nice to get this in so we can stop bugging Mailchimp every few minutes; our task queues are full of bad emails being subscribed over and over again :-( ).

**Comment by erinzm** [comment]
I want to know if my rebased branch tests OK, but Travis is having problems.
:frown:

**Comment by erinzm** [comment]
Thanks @brad, after rebasing against upstream/master I broke my history vs the PR's :(
Your PR fixes it, so now I can rest assured that tests will pass :)

**Comment by brad** [comment]
No problem. I love to see Travis happy :neckbeard:

**Comment by erinzm** [comment]
Hey @brad, is this pushed to pledgedev?

**Comment by brad** [comment]
Don't think so, @jwhite66 has a way to specify a specific branch on pledgedev.

**Comment by erinzm** [comment]
Hey @aaronlifshin, can I test this out on pledgedev?

**Comment by aaronlifshin** [comment]
Pushed to pledgedev.

Please test it quickly, as it is now in the main branch.

A

**Comment by erinzm** [comment]
Testing...

**Comment by erinzm** [comment]
@aaronlifshin It "works", but it looks like this. Should it look like this?

screenshot from 2014-08-03 20 42 48

**Comment by erinzm** [comment]
I think it stripped the newlines. Any ideas @brad?

**Comment by aaronlifshin** [comment]
No.

It should not look like that.  Please fix it or roll it back.

A

**Comment by erinzm** [comment]
OK, looks like the newlines are wonky. Recreating the newlines in the
template files should work. But it's weird, the tests all pass.

**Comment by aaronlifshin** [comment]
@ArchimedesPi this one was an extremely frustrating pull request.  Now it's blocking priority work, and I have to fix and re-test the issues your changes have created.

**Comment by erinzm** [comment]
Sorry. Github has a "revert PR" button, you can use that to revert it.

**Comment by aaronlifshin** [comment]
I did.

**Comment by aaronlifshin** [comment]
No biggie, just reverted it.

**Pull request merged**
