### PR TITLE
More Jade-ification and cleanup

### PR DESCRIPTION
**Pull request by dklann**
Dunno if these will make it to production, but they will be a little cleaner if they do. They all look reasonable on localhost:8080  ~d

### CODE REVIEW

**Comment by brad** [comment]
Thanks for removing those stray `p` tags. Looks like there's a few more in `more.jade` and `learnmore.jade`

**Comment by brad** [comment]
I just have one more tiny request @dklann. In `aboutus.jade` you changed a link from absolute to relative. Can you please change it back? We made all the links absolute on purpose so that if people manage to find their way here, they will be pushed back to mayone.us if they click any links.

**Comment by dklann** [comment]
Was that the link to 'privacy-policy' ? The copy I edited was missing the protocol specifier (http[s]:). I'll simply add that if that's what you're talking about. Thanks!

**Comment by brad** [comment]
That's the one, but the missing protocol specifier is intentional, so that linked page uses the same protocol as the page the user was on.

**Comment by dklann** [comment]
Holy crap! That's a convenient feature I wasn't previously aware of! Nice. I'll put it back the way it was. Coming up ...

**Comment by brad** [comment]
Thanks!

**Pull request merged**
