### PR TITLE
query pledge table for team-specific embed data

### PR DESCRIPTION
**Pull request by jtolio**
should we do shared counters for every team?

### CODE REVIEW

**Comment by hjfreyer** [comment]
Let's skip the sharded counters for now, and keep an eye on the team size distribution. I was lazy and I fixed the sharding factor at 50, and the majority of teams will not get 50 pledges, but I can see some celebrity getting > 1000 potentially, in which case we'll need to optimize. It's a bit of a pain to fix it later but not too bad.

Could you do me a favor, and replicate this handler in handlers.py? Bind it to '/r/total', and then we can return some proper JSON and actually test it, and deprecate the current handler thereafter. If you're strapped for time, leave any of that as a TODO against me.

**Comment by hjfreyer** [comment]
This is fine. We can put it in a better place soon. LGTM

**Comment by jtolio** [comment]
lemme know when this is deployed i guess

**Comment by aaronlifshin** [comment]
Any reason I should deploy it?

A

**Comment by aaronlifshin** [comment]
Ooops... that was meant to say "any reason I shouldn't deploy it"

Instead it came out totally rude.  Fast typing :(

A

**Pull request merged**
