### PR TITLE
Switch embed to use a $6M target, and to count days again.

### PR DESCRIPTION
**Pull request by jwhite66**
Addresses issue https://github.com/MayOneUS/pledgeservice/issues/71

May not be the best fix; it doesn't have the segmented thermometer bits.

### CODE REVIEW

**Comment by aaronlifshin** [comment]
This is not the way.  We should be at goal of 5M and subtracting 1M from the total.

**Comment by jwhite66** [comment]
I tried it that way; you get a really tiny sliver of a progress bar to start, which I think is deceptively discouraging.  I'd suggest starting this way; we can shift to a (x - 1M)/5M strategy after x becomes substantially bigger than 1M.  Alternately, someone could do a thermometer style thing instead.

**Comment by aaronlifshin** [comment]
The requirement of showing 200k+ out of 5M comes direct from Lessig.

There have been a lot of objections from all quarters to mitigate the
perception of our goal in some way.  But he doesn't want to hide from it.
 And he is sick of it not being 100% reflected.

We are in a campaign to raise 5M in a month of go bust, and we want the
assets on the site honestly to reflect this.

x will become substantially bigger in the next 2 days.

A

**Comment by aaronlifshin** [comment]
Oh man, I was kind of hoping you could change your code to make it (x-1 out
of 5).

A

**Comment by jwhite66** [comment]
Heh.  Sorry; didn't set that trail up quite right.

**Pull request closed without merging**
