### PR TITLE
install test libraries with pip

### PR DESCRIPTION
**Pull request by brad**
@hjfreyer This change removes the testlib folder and installs test libraries with pip instead. I want to pass it by you in case you had a good reason for including them.

### CODE REVIEW

**Comment by hjfreyer** [comment]
My justification is that the less setup there is, the better. I was actually thinking of taking this in the other direction and including the App Engine SDK in the repo.

Disk space is much much cheaper than developer time, so if including the libs makes life at all easier, I'd rather do it that way. Is the fact that they're there interfering somehow?

**Comment by brad** [comment]
No, it just feels wrong...
Do all the licenses allow us to do this?

**Comment by jtolio** [comment]
+1 on making sure to check in license files when redistributing other works

**Comment by brad** [comment]
OK, for the sake of ease of development for new contributors, I'm closing this.

**Pull request closed without merging**
